// -----------------------------------------------------------------------------
// Letter quality — the tells a human reads in ten seconds.
//
// 2026-09-12: an employment letter printed its own phone number two ways
// (416 4278441 in the header, 416 427 4881 in the body) and spelled "Human
// resourses"; the matching stubs said "Comunications Manager". Genuine HR
// letters and payroll stubs are generated from templates that do not drift
// like that. Deterministic, per document.
// -----------------------------------------------------------------------------

import type { ForensicFlag } from './types'

const MISSPELLINGS: Array<[RegExp, string]> = [
  [/\bresourses?\b/i, 'resources'], [/\bcomunications?\b/i, 'communications'], [/\brecieve[ds]?\b/i, 'receive'],
  [/\bmanagment\b/i, 'management'], [/\bseperate\b/i, 'separate'], [/\baddres\b|\badress\b/i, 'address'],
  [/\boccured\b/i, 'occurred'], [/\bwich\b/i, 'which'], [/\bbuisness\b/i, 'business'], [/\bsalery\b/i, 'salary'],
  [/\bpositon\b/i, 'position'], [/\baccomodation\b/i, 'accommodation'], [/\brefrence\b/i, 'reference'],
  [/\bsincerly\b/i, 'sincerely'], [/\bgaurantee\b/i, 'guarantee'], [/\bdefinately\b/i, 'definitely'],
  [/\bemploye\b/i, 'employee'], [/\bcompnay\b/i, 'company'], [/\bcurently\b/i, 'currently'], [/\bpermenant\b/i, 'permanent'],
  [/\bfull[- ]tiem\b/i, 'full-time'], [/\bconfrim\b/i, 'confirm'], [/\bdepartement\b/i, 'department'],
]

function phones(text: string): string[] {
  const out = new Set<string>()
  for (const m of (text || '').matchAll(/(?:\+?1[\s.-]?)?\(?([2-9]\d{2})\)?[\s.-]?(\d{3})[\s.-]?(\d{4})\b/g)) out.add(`${m[1]}${m[2]}${m[3]}`)
  return Array.from(out)
}

function editDistance1(a: string, b: string): boolean {
  if (a.length !== b.length) return false
  const diff = [...a].map((c, i) => c !== b[i] ? i : -1).filter(i => i >= 0)
  if (diff.length === 1) return true
  if (diff.length === 2 && diff[1] === diff[0] + 1 && a[diff[0]] === b[diff[1]] && a[diff[1]] === b[diff[0]]) return true
  return false
}

export function checkLetterQuality(text: string, file: string, kind: string): ForensicFlag[] {
  const flags: ForensicFlag[] = []
  const t = text || ''
  if (!t) return flags
  // 1. The letter's own phone number printed two ways.
  // Two numbers on the same exchange that differ in the last four digits,
  // and nothing else — "416 4278441" in the header, "416 427 4881" in the
  // body. A main line and a fax would be labelled; a letter typed by hand
  // drifts. One digit apart is near-certain; otherwise say which to verify.
  // A number labelled fax / télécopieur / direct / ext / cell is a second
  // line by design, not the main line printed two ways (review 2026-09-13).
  const unlabelled = t.replace(/\b(?:fax|t[ée]l[ée]copieur|direct(?:\s*line)?|ext\.?|extension|cell(?:ular)?|mobile)\b\s*[:.#-]?\s*(?:\+?1[\s.-]?)?\(?[2-9]\d{2}\)?[\s.-]?\d{3}[\s.-]?\d{4}/gi, ' ')
  const ph = phones(unlabelled)
  outer: for (let i = 0; i < ph.length; i++) for (let j = i + 1; j < ph.length; j++) {
    if (ph[i].slice(0, 6) === ph[j].slice(0, 6) && ph[i] !== ph[j]) {
      const close = editDistance1(ph[i], ph[j])
      const fmt = (p: string) => `${p.slice(0, 3)}-${p.slice(3, 6)}-${p.slice(6)}`
      flags.push({ code: 'letter_phone_inconsistent', severity: close ? 'medium' : 'low', file,
        evidence_en: `The document prints its own contact number two different ways: ${fmt(ph[i])} and ${fmt(ph[j])}${close ? ' (one digit differs)' : ''}. A letterhead generated by the employer's system carries one number; a hand-edited letter drifts. Verify through a number found independently (registry, website), not one on the letter.`,
        evidence_zh: `文件里自己的联系电话有两种写法：${fmt(ph[i])} 与 ${fmt(ph[j])}${close ? '（一位数字不同）' : ''}。雇主系统生成的信头只有一个号码；手工改过的信才会前后不一。核实时请用独立来源（注册库、官网）的号码，不要用信上的。` })
      break outer
    }
  }
  // 2. Misspellings on a formal document.
  const found: string[] = []
  for (const [re, right] of MISSPELLINGS) { const m = t.match(re); if (m) found.push(`"${m[0]}" (${right})`) }
  if (found.length) {
    flags.push({ code: 'document_spelling_errors', severity: found.length >= 2 ? 'medium' : 'low', file,
      evidence_en: `${found.length} spelling error(s) on a ${kind.replace(/_/g, ' ')}: ${found.slice(0, 4).join(', ')}. HR templates and payroll software do not misspell their own field labels; typed-up documents do.`,
      evidence_zh: `${kind.includes('pay_stub') ? '工资单' : '信函'}上有 ${found.length} 处拼写错误：${found.slice(0, 4).join('、')}。HR 模板和工资软件不会拼错自己的栏目名，手打的文件才会。` })
  }
  return flags
}
