// -----------------------------------------------------------------------------
// P0 — PDF Metadata Forensics
//
// Reads PDF Title / Producer / Creator / CreationDate / ModificationDate using
// pdf-lib (pure JS, edge-runtime compatible). Then applies heuristics to flag
// PDFs that look like they were created by manually re-saving a screenshot,
// rather than being generated by the original source server (bank, Equifax,
// employer payroll system).
//
// Real bank/credit-bureau PDFs have specific Producer signatures:
//   - CIBC online statements: "iText" (varies by version, e.g. "iText 5.5.13")
//   - RBC online statements: "Adobe Acrobat" or "Apache FOP"
//   - TD online statements:   "Apache FOP"
//   - Equifax credit reports: server-generated text PDF (specific layout)
//   - ADP / Ceridian paystubs: "Apache FOP" or "Crystal Reports"
//
// Forged PDFs almost always come from re-saving a doctored screenshot, so the
// Producer ends up being the user's local image-to-PDF converter:
//   - macOS Preview:  Producer="macOS Version X.Y.Z (Build) Quartz PDFContext"
//                     Creator="Preview" (often, not always)
//   - Microsoft Word: Producer="Microsoft Word" or "Microsoft® Word for Microsoft 365"
//   - Skia (Chrome Print to PDF): Producer="Skia/PDF m1XX"
//   - Pages (macOS):  Producer="macOS Version X.Y.Z Quartz PDFContext"
//                     Creator="Pages"
//   - GIMP/Photoshop export: Producer contains "GIMP" or "Adobe Photoshop"
//
// We also flag titles that mention PNG/JPEG/screenshot — these strings only
// appear in the title field when the user manually saved a screenshot file.
// Real bank PDFs have titles like "Account_Statement_2026-03.pdf" or empty.
// -----------------------------------------------------------------------------

import { PDFDocument } from 'pdf-lib'
import type { ForensicFlag, PdfMetadataResult } from './types'

// ---------------------------------------------------------------------------
// Raw PDF byte parser — reads Info dictionary directly from the binary stream.
// pdf-lib's PDFDocument.load() can contaminate Producer/Creator/ModDate with
// its own values. This parser reads the ACTUAL bytes to get ground-truth metadata.
// ---------------------------------------------------------------------------

function parseRawPdfMetadata(bytes: Uint8Array): Partial<PdfMetadataResult> | null {
  try {
    const text = new TextDecoder('ascii', { fatal: false }).decode(bytes)

    // Find trailer → /Info reference (e.g. "/Info 3 0 R")
    const trailerIdx = text.lastIndexOf('trailer')
    const xrefStreamInfo = trailerIdx < 0
      ? text.match(/\/Info\s+(\d+)\s+\d+\s+R/)?.[1]
      : null
    let infoObjNum: string | null = null
    if (trailerIdx >= 0) {
      const trailerBlock = text.substring(trailerIdx, Math.min(text.length, trailerIdx + 500))
      infoObjNum = trailerBlock.match(/\/Info\s+(\d+)\s+\d+\s+R/)?.[1] ?? null
    } else if (xrefStreamInfo) {
      infoObjNum = xrefStreamInfo
    }
    if (!infoObjNum) {
      // Some PDFs embed Info inline — scan for /Producer in any dict
      const prodMatch = text.match(/\/Producer\s*(\(|<)/)
      if (!prodMatch) return null
    }

    // Find the Info object: "N 0 obj << ... >> endobj"
    let infoBlock: string | null = null
    if (infoObjNum) {
      const objPattern = new RegExp(`${infoObjNum}\\s+0\\s+obj\\s*`, 'g')
      const m = objPattern.exec(text)
      if (m) {
        const start = m.index + m[0].length
        const endObj = text.indexOf('endobj', start)
        if (endObj > start) infoBlock = text.substring(start, endObj)
      }
    }
    // Fallback: find the first dict containing /Producer
    if (!infoBlock) {
      const prodIdx = text.indexOf('/Producer')
      if (prodIdx < 0) return null
      const dictStart = text.lastIndexOf('<<', prodIdx)
      const dictEnd = text.indexOf('>>', prodIdx)
      if (dictStart >= 0 && dictEnd > dictStart) {
        infoBlock = text.substring(dictStart, dictEnd + 2)
      }
    }
    if (!infoBlock) return null

    const extractValue = (key: string): string | null => {
      const keyIdx = infoBlock!.indexOf(`/${key}`)
      if (keyIdx < 0) return null
      const afterKey = infoBlock!.substring(keyIdx + key.length + 1).trimStart()

      // Hex string: <4865...>
      if (afterKey.startsWith('<') && !afterKey.startsWith('<<')) {
        const end = afterKey.indexOf('>')
        if (end < 0) return null
        const hex = afterKey.substring(1, end).replace(/\s/g, '')
        // UTF-16 BOM
        if (hex.startsWith('FEFF') || hex.startsWith('feff')) {
          const u16bytes: number[] = []
          for (let i = 4; i < hex.length; i += 4) {
            u16bytes.push(parseInt(hex.substring(i, i + 4), 16))
          }
          return String.fromCharCode(...u16bytes)
        }
        const asciiBytes: number[] = []
        for (let i = 0; i < hex.length; i += 2) {
          asciiBytes.push(parseInt(hex.substring(i, i + 2), 16))
        }
        return String.fromCharCode(...asciiBytes)
      }

      // Literal string: (text with \( escapes)
      if (afterKey.startsWith('(')) {
        let depth = 0
        let escaped = false
        let result = ''
        for (let i = 0; i < afterKey.length; i++) {
          const c = afterKey[i]
          if (escaped) {
            if (c === 'n') result += '\n'
            else if (c === 'r') result += '\r'
            else if (c === 't') result += '\t'
            else result += c
            escaped = false
            continue
          }
          if (c === '\\') { escaped = true; continue }
          if (c === '(') { depth++; if (depth > 1) result += c; continue }
          if (c === ')') { depth--; if (depth === 0) break; result += c; continue }
          if (depth >= 1) result += c
        }
        // Handle UTF-16 BOM in literal strings
        if (result.charCodeAt(0) === 0xFE && result.charCodeAt(1) === 0xFF) {
          const u16: number[] = []
          for (let i = 2; i < result.length; i += 2) {
            u16.push((result.charCodeAt(i) << 8) | result.charCodeAt(i + 1))
          }
          return String.fromCharCode(...u16)
        }
        return result
      }
      return null
    }

    const parsePdfDate = (raw: string | null): string | null => {
      if (!raw) return null
      // Format: D:YYYYMMDDHHmmSS+HH'MM' or D:YYYYMMDDHHmmSS-HH'MM'
      const m = raw.match(/D:(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})([+-]\d{2})'(\d{2})'?/)
      if (m) {
        const [, y, mo, d, h, mi, s, tzH, tzM] = m
        return `${y}-${mo}-${d}T${h}:${mi}:${s}${tzH}:${tzM}`
      }
      // Simpler format without timezone
      const m2 = raw.match(/D:(\d{4})(\d{2})(\d{2})(\d{2})?(\d{2})?(\d{2})?/)
      if (m2) {
        const [, y, mo, d, h = '00', mi = '00', s = '00'] = m2
        return `${y}-${mo}-${d}T${h}:${mi}:${s}Z`
      }
      return null
    }

    return {
      title: extractValue('Title') || null,
      author: extractValue('Author') || null,
      subject: extractValue('Subject') || null,
      producer: extractValue('Producer') || null,
      creator: extractValue('Creator') || null,
      creation_date: parsePdfDate(extractValue('CreationDate')),
      modification_date: parsePdfDate(extractValue('ModDate')),
    }
  } catch {
    return null
  }
}

/** Document kinds where forged screenshots are most common (bank docs,
 *  credit reports, paystubs) — we apply stricter Producer rules to these. */
const STRICT_KINDS = new Set([
  'bank_statement',
  'credit_report',
  'pay_stub',
  'employment_letter',
])

/** IMAGE EDITING tools — if a "bank statement" or "pay stub" was produced by
 *  Photoshop/GIMP/Canva, it's almost certainly doctored. CRITICAL severity. */
const EDITING_TOOL_PATTERNS: Array<{ pattern: RegExp; tool: string }> = [
  { pattern: /GIMP/i,                       tool: 'GIMP image editor' },
  { pattern: /Photoshop/i,                  tool: 'Adobe Photoshop' },
  { pattern: /Canva/i,                      tool: 'Canva' },
  { pattern: /Illustrator/i,               tool: 'Adobe Illustrator' },
  { pattern: /Affinity/i,                   tool: 'Affinity Designer/Photo' },
  { pattern: /Pixelmator/i,                 tool: 'Pixelmator' },
]

/** DOCUMENT CREATION tools — ambiguous for strict doc types (bank/credit/pay).
 *  A real bank statement should never come from Word, but an employment letter
 *  created in Word is normal. Severity depends on doc kind. */
const DOC_CREATION_PATTERNS: Array<{ pattern: RegExp; tool: string }> = [
  { pattern: /Microsoft\s*Word/i,           tool: 'Microsoft Word' },
  { pattern: /Microsoft.*Office/i,          tool: 'Microsoft Office' },
  { pattern: /Pages\s+\d/i,                 tool: 'Apple Pages' },
  { pattern: /LibreOffice/i,                tool: 'LibreOffice' },
  { pattern: /OpenOffice/i,                 tool: 'OpenOffice' },
  { pattern: /Google\s*Docs/i,              tool: 'Google Docs export' },
]

/** SCAN / PRINT-TO-PDF tools — LEGITIMATE for scanned documents.
 *  ID cards, signed letters, and printed statements are commonly scanned
 *  via phone camera, iOS Notes, or "Print to PDF". NOT a fraud signal. */
const SCAN_PRINT_PATTERNS: Array<{ pattern: RegExp; tool: string }> = [
  { pattern: /Quartz\s*PDFContext/i,        tool: 'macOS/iOS Quartz (scan/print)' },
  { pattern: /Skia[\/\s]?PDF/i,             tool: 'Chrome Print-to-PDF' },
  { pattern: /Microsoft.*Print\s*To\s*PDF/i, tool: 'Microsoft Print to PDF' },
  { pattern: /CamScanner/i,                 tool: 'CamScanner' },
  { pattern: /Adobe\s*Scan/i,               tool: 'Adobe Scan' },
  { pattern: /Microsoft\s*Lens/i,           tool: 'Microsoft Lens' },
]

/** IMAGE-TO-PDF converters — suspicious when doc kind is strict. */
const IMAGE_CONVERTER_PATTERNS: Array<{ pattern: RegExp; tool: string }> = [
  { pattern: /Image2PDF/i,                  tool: 'Image2PDF converter' },
  { pattern: /jpeg2pdf|jpg2pdf|png2pdf/i,   tool: 'image-to-PDF converter' },
]

/** Combined list of all non-server tools (for backwards compat with existing logic). */
const SCREENSHOT_PRODUCER_PATTERNS: Array<{ pattern: RegExp; tool: string }> = [
  ...EDITING_TOOL_PATTERNS,
  ...DOC_CREATION_PATTERNS,
  ...IMAGE_CONVERTER_PATTERNS,
  // NOTE: SCAN_PRINT_PATTERNS deliberately excluded — scanning is legitimate
]

/** Producer/Creator strings indicating a real server-generated PDF.
 *  Presence does NOT prove authenticity (a sophisticated forger could spoof
 *  the metadata) but absence of these in conjunction with screenshot tools
 *  is strong evidence of forgery. */
const TRUSTED_PRODUCER_PATTERNS: RegExp[] = [
  /\biText/i,                  // CIBC, BMO, Apryse/Workday, iTextSharp (.NET), Java enterprise PDFs
  /Apache\s*FOP/i,            // RBC, TD, payroll systems
  /Crystal\s*Reports/i,       // ADP, Ceridian, enterprise reports
  /Xenos/i,                   // ADP AutoPay statement pipeline ("PDFOUT vX.X by Xenos, inc." — AFP/Metacode→PDF conversion)
  /Adobe\s*PDF\s*Library/i,   // Adobe enterprise tooling
  /Prince\s*[\d.]/i,          // Prince XML — common for fintech
  /wkhtmltopdf/i,             // server-side rendering (less trusted but common)
  /PDFKit/i,                  // Node.js PDFKit — server-generated
  /ReportLab/i,               // Python ReportLab — server-generated
  /TCPDF/i,                   // PHP TCPDF — server-generated
  /FPDF/i,                    // PHP FPDF — server-generated
  /OpenPDF/i,                 // Java OpenPDF — server-generated
]

/** Known server-side rendering engines that are also used by forgers.
 *  These are NOT trusted, but they ARE recognized — so they shouldn't
 *  trigger "unknown producer". pdf-structure.ts handles the deeper
 *  content-aware check for these tools. */
const RECOGNIZED_PRODUCER_PATTERNS: RegExp[] = [
  /pdf-lib/i,                 // Workday, Gusto, BambooHR payroll AND forgers
  /jsPDF/i,                   // some enterprise + many forgers
  /pdfmake/i,                 // some enterprise + forgers
]

/** Title patterns that indicate the source file was an image (PNG/JPEG/screenshot)
 *  before being converted to PDF — strong fraud signal. */
const IMAGE_TITLE_PATTERN = /\b(PNG|JPEG|JPG|screenshot|screen[\s-]?shot|image|scan|untitled|export)\b/i

/**
 * Read PDF metadata. Returns null if the buffer isn't a parseable PDF.
 *
 * Primary source: raw byte parser (reads Info dict directly from the binary).
 * pdf-lib is used ONLY for page_count (requires understanding the page tree).
 * This avoids pdf-lib contaminating Producer/Creator/ModDate with its own values.
 */
export async function readPdfMetadata(
  bytes: ArrayBuffer | Uint8Array
): Promise<PdfMetadataResult | null> {
  try {
    const u8 = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes)
    const fileSize = u8.byteLength

    // Raw byte parse — ground truth for Producer/Creator/dates
    const raw = parseRawPdfMetadata(u8)

    // pdf-lib — only for page_count (and fallback metadata if raw parse missed)
    const doc = await PDFDocument.load(u8, {
      ignoreEncryption: true,
      throwOnInvalidObject: false,
      updateMetadata: false,
    })

    return {
      title: raw?.title ?? doc.getTitle() ?? null,
      author: raw?.author ?? doc.getAuthor() ?? null,
      subject: raw?.subject ?? doc.getSubject() ?? null,
      producer: raw?.producer ?? doc.getProducer() ?? null,
      creator: raw?.creator ?? doc.getCreator() ?? null,
      creation_date: raw?.creation_date ?? doc.getCreationDate()?.toISOString() ?? null,
      modification_date: raw?.modification_date ?? doc.getModificationDate()?.toISOString() ?? null,
      page_count: doc.getPageCount(),
      file_size_bytes: fileSize,
    }
  } catch {
    return null
  }
}

/**
 * Apply metadata-based fraud heuristics. Returns a list of ForensicFlag
 * objects. The `file` and `kind` arguments are used to make the flags
 * actionable and for kind-specific rules (e.g. bank statement strictness).
 */
export function checkPdfMetadata(
  meta: PdfMetadataResult,
  file: string,
  kind: string
): ForensicFlag[] {
  const flags: ForensicFlag[] = []
  const isStrict = STRICT_KINDS.has(kind)
  const producer = meta.producer || ''
  const creator = meta.creator || ''
  const title = meta.title || ''
  const combined = `${producer} ${creator}`

  // ---------------------------------------------------------------------------
  // Rule 1: Check Producer/Creator against categorized tool lists.
  //
  // Image EDITING tools (Photoshop, GIMP, Canva) → always suspicious
  // Doc CREATION tools (Word, Pages) → suspicious for bank/credit/pay, but
  //   normal for employment_letter and offer_letter
  // SCAN/PRINT tools (iOS Notes, Print to PDF) → LEGITIMATE for all types,
  //   because people commonly scan/photo physical documents
  // IMAGE CONVERTERS (Image2PDF) → suspicious for strict doc types
  // ---------------------------------------------------------------------------
  let producerFlagged = false

  // 1a. Editing tools — always suspicious for any strict kind
  for (const { pattern, tool } of EDITING_TOOL_PATTERNS) {
    if (pattern.test(combined)) {
      flags.push({
        code: 'pdf_producer_consumer_tool',
        severity: isStrict ? 'critical' : 'high',
        file,
        evidence_en: `PDF Producer="${producer || creator}" indicates ${tool} — an image editing tool. Documents edited in ${tool} are highly likely to be tampered.`,
        evidence_zh: `PDF 生成工具为 "${producer || creator}"（${tool}），这是图片编辑软件。经过 ${tool} 编辑的文件极可能被篡改。`,
      })
      producerFlagged = true
      break
    }
  }

  // 1b. Doc creation tools — suspicious for bank_statement/credit_report/pay_stub
  //     but NORMAL for employment_letter/offer_letter (often typed in Word).
  //     Pay stubs get their OWN code: very small employers genuinely produce
  //     stubs from Word/Excel templates, so a Word stub is a high-severity
  //     verify signal but NOT the standalone producer_consumer_tool hard gate
  //     that bank statements and credit reports (never legitimately produced
  //     by Word) carry.
  if (!producerFlagged) {
    const docToolGating = kind === 'bank_statement' || kind === 'credit_report'
    const docToolSuspicious = docToolGating || kind === 'pay_stub'
    for (const { pattern, tool } of DOC_CREATION_PATTERNS) {
      if (pattern.test(combined)) {
        if (docToolSuspicious) {
          flags.push({
            code: docToolGating ? 'pdf_producer_consumer_tool' : 'pdf_producer_paystub_doc_tool',
            severity: 'high',
            file,
            evidence_en: `PDF Producer="${producer || creator}" indicates ${tool}. Real ${kind.replace('_', ' ')} PDFs are ${docToolGating ? 'server-generated — ' + tool + ' suggests manual creation.' : 'usually server-generated; ' + tool + ' is consistent with a very small employer\'s manual template, but also with fabrication — verify with the employer.'}`,
            evidence_zh: `PDF 生成工具为 "${producer || creator}"（${tool}）。${docToolGating ? `真实的${zhKind(kind)}由服务器生成，${tool} 表明是手工制作的。` : `真实的${zhKind(kind)}通常由工资系统生成；${tool} 可能是小微雇主手工模板，也可能是伪造——建议向雇主核实。`}`,
          })
          producerFlagged = true
        }
        // For employment_letter/offer_letter, Word/Pages is normal — no flag
        break
      }
    }
  }

  // 1c. Image converters — suspicious for strict kinds
  if (!producerFlagged) {
    for (const { pattern, tool } of IMAGE_CONVERTER_PATTERNS) {
      if (pattern.test(combined)) {
        flags.push({
          code: 'pdf_producer_consumer_tool',
          severity: isStrict ? 'high' : 'medium',
          file,
          evidence_en: `PDF Producer="${producer || creator}" indicates ${tool}. Official documents are not typically distributed as converted images.`,
          evidence_zh: `PDF 生成工具为 "${producer || creator}"（${tool}）。正式文件通常不会以图片转换的方式发放。`,
        })
        producerFlagged = true
        break
      }
    }
  }

  // 1d. Scan/print tools — LEGITIMATE, no flag. iOS Notes, Print to PDF,
  //     CamScanner etc. are standard ways to digitize physical documents.

  // ---------------------------------------------------------------------------
  // Rule 2: Title or Subject mentions image/screenshot extension. The Title
  // field in a real bank PDF is either empty or the account/statement number.
  // It would NEVER contain "PNG" or "screenshot".
  // ---------------------------------------------------------------------------
  if (IMAGE_TITLE_PATTERN.test(title) || IMAGE_TITLE_PATTERN.test(meta.subject || '')) {
    flags.push({
      code: 'pdf_title_indicates_image',
      severity: isStrict ? 'critical' : 'high',
      file,
      evidence_en: `PDF internal title="${title || meta.subject}" indicates the source was an image file (PNG/JPEG/screenshot) before being converted to PDF.`,
      evidence_zh: `PDF 内部标题="${title || meta.subject}"，说明源文件是图片（PNG/JPEG/截图），后被转换成 PDF。`,
    })
  }

  // ---------------------------------------------------------------------------
  // Rule 3: For strict kinds, having NO trusted producer string is itself a
  // soft warning. Combined with Rule 1 it's already critical; standalone it's
  // medium.
  // ---------------------------------------------------------------------------
  if (isStrict) {
    const hasTrusted = TRUSTED_PRODUCER_PATTERNS.some(p => p.test(combined))
    const hasScreenshotTool = SCREENSHOT_PRODUCER_PATTERNS.some(({ pattern }) => pattern.test(combined))
    const hasRecognized = RECOGNIZED_PRODUCER_PATTERNS.some(p => p.test(combined))
    if (!hasTrusted && !hasScreenshotTool && !hasRecognized && producer) {
      flags.push({
        code: 'pdf_producer_unknown',
        severity: 'low',
        file,
        evidence_en: `PDF Producer="${producer}" is not in the known whitelist of bank/payroll systems. Authentic source could not be confirmed from metadata alone.`,
        evidence_zh: `PDF 生成工具="${producer}" 不在已知的银行/工资系统白名单中。仅凭元数据无法确认文件出处。`,
      })
    }
  }

  // ---------------------------------------------------------------------------
  // Rule 4: Metadata stripped (no Producer at all). Common in re-saved PDFs.
  // Real server-generated PDFs always set Producer.
  // ---------------------------------------------------------------------------
  if (!producer && !creator && isStrict) {
    flags.push({
      code: 'pdf_metadata_stripped',
      severity: 'medium',
      file,
      evidence_en: `PDF has no Producer or Creator metadata. Authentic ${kind || 'official'} PDFs always include their generating tool.`,
      evidence_zh: `PDF 完全没有生成工具元数据。真实的${zhKind(kind)}文件总会包含生成工具信息。`,
    })
  }

  // ---------------------------------------------------------------------------
  // Rule 5: Fresh creation timestamp. Real bank statements and pay stubs are
  // dated as of the statement/pay period (often weeks before download); a
  // fresh CreationDate matching ModDate exactly suggests "just built from
  // scratch".
  //
  // EXCLUDES kinds that are EXPECTED to be freshly downloaded:
  //   - credit_report — landlords always pull a fresh copy from the bureau
  //   - employment_letter — agents commonly export/sign these the same day
  //   - id_document — passports/licences are routinely re-scanned on demand
  //   - other / bundled exports — agent packets export to PDF on demand
  // The rule still fires for bank_statement and pay_stub where freshness IS
  // suspicious.
  // ---------------------------------------------------------------------------
  const FRESHNESS_KINDS = new Set(['bank_statement', 'pay_stub'])
  if (
    FRESHNESS_KINDS.has(kind) &&
    meta.creation_date &&
    meta.modification_date &&
    meta.creation_date === meta.modification_date
  ) {
    const created = new Date(meta.creation_date).getTime()
    const ageHours = (Date.now() - created) / (1000 * 60 * 60)
    if (ageHours < 24 * 7 && ageHours >= 0) {
      flags.push({
        code: 'pdf_freshly_created',
        severity: 'medium',
        file,
        evidence_en: `${kind} PDF was created within the past ${Math.round(ageHours)}h with CreationDate==ModificationDate. Authentic ${kind === 'bank_statement' ? 'bank statements' : 'pay stubs'} are typically weeks-to-months old by the time they're shared with a landlord.`,
        evidence_zh: `${zhKind(kind)} PDF 创建时间在 ${Math.round(ageHours)} 小时内，且创建时间等于修改时间。真实的${zhKind(kind)}给到房东时通常已经存在好几周到几个月。`,
      })
    }
  }

  // ---------------------------------------------------------------------------
  // Rule 6: For strict kinds, single-page PDFs are suspicious. Real bank
  // statements are typically 2-6 pages; credit reports are 5-20 pages.
  // ---------------------------------------------------------------------------
  if (isStrict && meta.page_count === 1 && (kind === 'bank_statement' || kind === 'credit_report')) {
    flags.push({
      code: 'pdf_unusually_short',
      severity: 'low',
      file,
      evidence_en: `${kind} is only 1 page. Authentic ${kind === 'bank_statement' ? 'bank statements (2-6 pages)' : 'credit reports (5-20 pages)'} are typically longer.`,
      evidence_zh: `${zhKind(kind)}只有 1 页。真实的${kind === 'bank_statement' ? '银行对账单通常 2-6 页' : '信用报告通常 5-20 页'}。`,
    })
  }

  return flags
}

function zhKind(kind: string): string {
  switch (kind) {
    case 'bank_statement': return '银行对账单'
    case 'credit_report': return '信用报告'
    case 'pay_stub': return '工资单'
    case 'employment_letter': return '雇佣证明信'
    case 'id_document': return '身份证件'
    case 'reference': return '推荐信'
    case 'offer_letter': return 'Offer Letter'
    default: return '官方文件'
  }
}
