// -----------------------------------------------------------------------------
// P0 — PDF Metadata Forensics
//
// Reads PDF Title / Producer / Creator / CreationDate / ModificationDate using
// pdf-lib (pure JS, edge-runtime compatible). Then applies heuristics to flag
// PDFs that look like they were created by manually re-saving a screenshot,
// rather than being generated by the original source server (bank, Equifax,
// employer payroll system).
//
// Real bank/credit-bureau PDFs have specific Producer signatures:
//   - CIBC online statements: "iText" (varies by version, e.g. "iText 5.5.13")
//   - RBC online statements: "Adobe Acrobat" or "Apache FOP"
//   - TD online statements:   "Apache FOP"
//   - Equifax credit reports: server-generated text PDF (specific layout)
//   - ADP / Ceridian paystubs: "Apache FOP" or "Crystal Reports"
//
// Forged PDFs almost always come from re-saving a doctored screenshot, so the
// Producer ends up being the user's local image-to-PDF converter:
//   - macOS Preview:  Producer="macOS Version X.Y.Z (Build) Quartz PDFContext"
//                     Creator="Preview" (often, not always)
//   - Microsoft Word: Producer="Microsoft Word" or "Microsoft® Word for Microsoft 365"
//   - Skia (Chrome Print to PDF): Producer="Skia/PDF m1XX"
//   - Pages (macOS):  Producer="macOS Version X.Y.Z Quartz PDFContext"
//                     Creator="Pages"
//   - GIMP/Photoshop export: Producer contains "GIMP" or "Adobe Photoshop"
//
// We also flag titles that mention PNG/JPEG/screenshot — these strings only
// appear in the title field when the user manually saved a screenshot file.
// Real bank PDFs have titles like "Account_Statement_2026-03.pdf" or empty.
// -----------------------------------------------------------------------------

import { PDFDocument } from 'pdf-lib'
import type { ForensicFlag, PdfMetadataResult } from './types'
import { computeFileKey, decryptObjectBytes, findEncryptInfos, parsePdfStringAt } from './pdf-decrypt'

// ---------------------------------------------------------------------------
// Raw PDF byte parser — reads Info dictionary directly from the binary stream.
// pdf-lib's PDFDocument.load() can contaminate Producer/Creator/ModDate with
// its own values. This parser reads the ACTUAL bytes to get ground-truth metadata.
// ---------------------------------------------------------------------------

function parseRawPdfMetadata(bytes: Uint8Array): Partial<PdfMetadataResult> | null {
  try {
    const text = new TextDecoder('ascii', { fatal: false }).decode(bytes)

    // Find trailer → /Info reference (e.g. "/Info 3 0 R")
    const trailerIdx = text.lastIndexOf('trailer')
    const xrefStreamInfo = trailerIdx < 0
      ? text.match(/\/Info\s+(\d+)\s+\d+\s+R/)?.[1]
      : null
    let infoObjNum: string | null = null
    if (trailerIdx >= 0) {
      const trailerBlock = text.substring(trailerIdx, Math.min(text.length, trailerIdx + 500))
      infoObjNum = trailerBlock.match(/\/Info\s+(\d+)\s+\d+\s+R/)?.[1] ?? null
    } else if (xrefStreamInfo) {
      infoObjNum = xrefStreamInfo
    }
    if (!infoObjNum) {
      // Some PDFs embed Info inline — scan for /Producer in any dict
      const prodMatch = text.match(/\/Producer\s*(\(|<)/)
      if (!prodMatch) return null
    }

    // Find the Info object: "N 0 obj << ... >> endobj"
    let infoBlock: string | null = null
    if (infoObjNum) {
      const objPattern = new RegExp(`${infoObjNum}\\s+0\\s+obj\\s*`, 'g')
      const m = objPattern.exec(text)
      if (m) {
        const start = m.index + m[0].length
        const endObj = text.indexOf('endobj', start)
        if (endObj > start) infoBlock = text.substring(start, endObj)
      }
    }
    // Fallback: find the first dict containing /Producer
    if (!infoBlock) {
      const prodIdx = text.indexOf('/Producer')
      if (prodIdx < 0) return null
      const dictStart = text.lastIndexOf('<<', prodIdx)
      const dictEnd = text.indexOf('>>', prodIdx)
      if (dictStart >= 0 && dictEnd > dictStart) {
        infoBlock = text.substring(dictStart, dictEnd + 2)
      }
    }
    if (!infoBlock) return null

    const extractValue = (key: string): string | null => {
      const keyIdx = infoBlock!.indexOf(`/${key}`)
      if (keyIdx < 0) return null
      const afterKey = infoBlock!.substring(keyIdx + key.length + 1).trimStart()

      // Hex string: <4865...>
      if (afterKey.startsWith('<') && !afterKey.startsWith('<<')) {
        const end = afterKey.indexOf('>')
        if (end < 0) return null
        const hex = afterKey.substring(1, end).replace(/\s/g, '')
        // UTF-16 BOM
        if (hex.startsWith('FEFF') || hex.startsWith('feff')) {
          const u16bytes: number[] = []
          for (let i = 4; i < hex.length; i += 4) {
            u16bytes.push(parseInt(hex.substring(i, i + 4), 16))
          }
          return String.fromCharCode(...u16bytes)
        }
        const asciiBytes: number[] = []
        for (let i = 0; i < hex.length; i += 2) {
          asciiBytes.push(parseInt(hex.substring(i, i + 2), 16))
        }
        return String.fromCharCode(...asciiBytes)
      }

      // Literal string: (text with \( escapes)
      if (afterKey.startsWith('(')) {
        let depth = 0
        let escaped = false
        let result = ''
        for (let i = 0; i < afterKey.length; i++) {
          const c = afterKey[i]
          if (escaped) {
            if (c === 'n') result += '\n'
            else if (c === 'r') result += '\r'
            else if (c === 't') result += '\t'
            else result += c
            escaped = false
            continue
          }
          if (c === '\\') { escaped = true; continue }
          if (c === '(') { depth++; if (depth > 1) result += c; continue }
          if (c === ')') { depth--; if (depth === 0) break; result += c; continue }
          if (depth >= 1) result += c
        }
        // Handle UTF-16 BOM in literal strings
        if (result.charCodeAt(0) === 0xFE && result.charCodeAt(1) === 0xFF) {
          const u16: number[] = []
          for (let i = 2; i < result.length; i += 2) {
            u16.push((result.charCodeAt(i) << 8) | result.charCodeAt(i + 1))
          }
          return String.fromCharCode(...u16)
        }
        return result
      }
      return null
    }

    const parsePdfDate = (raw: string | null): string | null => {
      if (!raw) return null
      // Format: D:YYYYMMDDHHmmSS+HH'MM' or D:YYYYMMDDHHmmSS-HH'MM'
      const m = raw.match(/D:(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})([+-]\d{2})'(\d{2})'?/)
      if (m) {
        const [, y, mo, d, h, mi, s, tzH, tzM] = m
        return `${y}-${mo}-${d}T${h}:${mi}:${s}${tzH}:${tzM}`
      }
      // Simpler format without timezone
      const m2 = raw.match(/D:(\d{4})(\d{2})(\d{2})(\d{2})?(\d{2})?(\d{2})?/)
      if (m2) {
        const [, y, mo, d, h = '00', mi = '00', s = '00'] = m2
        return `${y}-${mo}-${d}T${h}:${mi}:${s}Z`
      }
      return null
    }

    return {
      title: extractValue('Title') || null,
      author: extractValue('Author') || null,
      subject: extractValue('Subject') || null,
      producer: extractValue('Producer') || null,
      creator: extractValue('Creator') || null,
      creation_date: parsePdfDate(extractValue('CreationDate')),
      modification_date: parsePdfDate(extractValue('ModDate')),
    }
  } catch {
    return null
  }
}

/** Document kinds where forged screenshots are most common (bank docs,
 *  credit reports, paystubs) — we apply stricter Producer rules to these. */
const STRICT_KINDS = new Set([
  'bank_statement',
  'credit_report',
  'pay_stub',
  'employment_letter',
])

/** IMAGE EDITING tools — if a "bank statement" or "pay stub" was produced by
 *  Photoshop/GIMP/Canva, it's almost certainly doctored. CRITICAL severity. */
const EDITING_TOOL_PATTERNS: Array<{ pattern: RegExp; tool: string }> = [
  { pattern: /GIMP/i,                       tool: 'GIMP image editor' },
  { pattern: /Photoshop/i,                  tool: 'Adobe Photoshop' },
  { pattern: /Canva/i,                      tool: 'Canva' },
  { pattern: /Illustrator/i,               tool: 'Adobe Illustrator' },
  { pattern: /Affinity/i,                   tool: 'Affinity Designer/Photo' },
  { pattern: /Pixelmator/i,                 tool: 'Pixelmator' },
]

/** DOCUMENT CREATION tools — ambiguous for strict doc types (bank/credit/pay).
 *  A real bank statement should never come from Word, but an employment letter
 *  created in Word is normal. Severity depends on doc kind. */
const DOC_CREATION_PATTERNS: Array<{ pattern: RegExp; tool: string }> = [
  { pattern: /Microsoft\s*Word/i,           tool: 'Microsoft Word' },
  // Excel was missing: case 24's three "ADP" pay stubs carried
  // Producer "Microsoft® Excel® 2013" and matched nothing here.
  { pattern: /Microsoft\s*®?\s*Excel/i,     tool: 'Microsoft Excel' },
  { pattern: /Microsoft.*Office/i,          tool: 'Microsoft Office' },
  { pattern: /Numbers\s+\d/i,               tool: 'Apple Numbers' },
  { pattern: /Google\s*Sheets/i,            tool: 'Google Sheets export' },
  { pattern: /Pages\s+\d/i,                 tool: 'Apple Pages' },
  { pattern: /LibreOffice/i,                tool: 'LibreOffice' },
  { pattern: /OpenOffice/i,                 tool: 'OpenOffice' },
  { pattern: /Google\s*Docs/i,              tool: 'Google Docs export' },
]

/** SCAN / PRINT-TO-PDF tools — LEGITIMATE for scanned documents.
 *  ID cards, signed letters, and printed statements are commonly scanned
 *  via phone camera, iOS Notes, or "Print to PDF". NOT a fraud signal. */
const SCAN_PRINT_PATTERNS: Array<{ pattern: RegExp; tool: string }> = [
  { pattern: /Quartz\s*PDFContext/i,        tool: 'macOS/iOS Quartz (scan/print)' },
  { pattern: /Skia[\/\s]?PDF/i,             tool: 'Chrome Print-to-PDF' },
  { pattern: /Microsoft.*Print\s*To\s*PDF/i, tool: 'Microsoft Print to PDF' },
  { pattern: /CamScanner/i,                 tool: 'CamScanner' },
  { pattern: /Adobe\s*Scan/i,               tool: 'Adobe Scan' },
  { pattern: /Microsoft\s*Lens/i,           tool: 'Microsoft Lens' },
]

/** IMAGE-TO-PDF converters — suspicious when doc kind is strict. */
const IMAGE_CONVERTER_PATTERNS: Array<{ pattern: RegExp; tool: string }> = [
  { pattern: /Image2PDF/i,                  tool: 'Image2PDF converter' },
  { pattern: /jpeg2pdf|jpg2pdf|png2pdf/i,   tool: 'image-to-PDF converter' },
]

/** Combined list of all non-server tools (for backwards compat with existing logic). */
const SCREENSHOT_PRODUCER_PATTERNS: Array<{ pattern: RegExp; tool: string }> = [
  ...EDITING_TOOL_PATTERNS,
  ...DOC_CREATION_PATTERNS,
  ...IMAGE_CONVERTER_PATTERNS,
  // NOTE: SCAN_PRINT_PATTERNS deliberately excluded — scanning is legitimate
]

/** Producer/Creator strings indicating a real server-generated PDF.
 *  Presence does NOT prove authenticity (a sophisticated forger could spoof
 *  the metadata) but absence of these in conjunction with screenshot tools
 *  is strong evidence of forgery. */
const TRUSTED_PRODUCER_PATTERNS: RegExp[] = [
  /\biText/i,                  // CIBC, BMO, Apryse/Workday, iTextSharp (.NET), Java enterprise PDFs
  /Apache\s*FOP/i,            // RBC, TD, payroll systems
  /Crystal\s*Reports/i,       // ADP, Ceridian, enterprise reports
  /Xenos/i,                   // ADP AutoPay statement pipeline ("PDFOUT vX.X by Xenos, inc." — AFP/Metacode→PDF conversion)
  /Adobe\s*PDF\s*Library/i,   // Adobe enterprise tooling
  /Prince\s*[\d.]/i,          // Prince XML — common for fintech
  /wkhtmltopdf/i,             // server-side rendering (less trusted but common)
  /PDFKit/i,                  // Node.js PDFKit — server-generated
  /ReportLab/i,               // Python ReportLab — server-generated
  /TCPDF/i,                   // PHP TCPDF — server-generated
  /FPDF/i,                    // PHP FPDF — server-generated
  /OpenPDF/i,                 // Java OpenPDF — server-generated
]

/** Known server-side rendering engines that are also used by forgers.
 *  These are NOT trusted, but they ARE recognized — so they shouldn't
 *  trigger "unknown producer". pdf-structure.ts handles the deeper
 *  content-aware check for these tools. */
const RECOGNIZED_PRODUCER_PATTERNS: RegExp[] = [
  /pdf-lib/i,                 // Workday, Gusto, BambooHR payroll AND forgers
  /jsPDF/i,                   // some enterprise + many forgers
  /pdfmake/i,                 // some enterprise + forgers
]

/** Title patterns that indicate the source file was an image (PNG/JPEG/screenshot)
 *  before being converted to PDF — strong fraud signal. */
const IMAGE_TITLE_PATTERN = /\b(PNG|JPEG|JPG|screenshot|screen[\s-]?shot|image|scan|untitled|export)\b/i

/**
 * Read PDF metadata. Returns null if the buffer isn't a parseable PDF.
 *
 * Primary source: raw byte parser (reads Info dict directly from the binary).
 * pdf-lib is used ONLY for page_count (requires understanding the page tree).
 * This avoids pdf-lib contaminating Producer/Creator/ModDate with its own values.
 */
export async function readPdfMetadata(
  bytes: ArrayBuffer | Uint8Array
): Promise<PdfMetadataResult | null> {
  try {
    const u8 = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes)
    const fileSize = u8.byteLength

    // Raw byte parse — ground truth for Producer/Creator/dates when the Info
    // dictionary sits uncompressed in the byte stream. On an ENCRYPTED file
    // the raw strings are ciphertext (case 24's letter read back as
    // "¥ÕóÙä[úl…" for Producer), so raw is discarded and the decrypting deep
    // scan is authoritative.
    const isEncrypted = findEncryptInfos(u8).length > 0
    const raw = isEncrypted ? null : parseRawPdfMetadata(u8)

    // pdf-lib — page_count and fallback metadata. Its strict parser throws on
    // many EDITED files (incremental updates with rewritten xref streams) —
    // exactly the files this module most needs to see. A throw here must
    // never null the whole result: it is recorded as parse_failed and the
    // deep scan below recovers the fields.
    let doc: PDFDocument | null = null
    try {
      doc = await PDFDocument.load(u8, {
        ignoreEncryption: true,
        throwOnInvalidObject: false,
        updateMetadata: false,
      })
    } catch {
      doc = null
    }
    let pageCount = 0
    if (doc) {
      try { pageCount = doc.getPageCount() } catch { doc = null }
    }

    // Deep scan when neither the raw parse nor pdf-lib produced the core
    // fields (Info dict inside a compressed object stream, or pdf-lib dead).
    const needDeep = isEncrypted || (!raw?.producer && !raw?.creation_date && !(doc && (doc.getProducer() || doc.getCreationDate())))
    const deep = needDeep ? await deepScanPdfMetadata(u8) : null

    const safe = <T,>(fn: () => T): T | null => { try { return fn() } catch { return null } }
    if (isEncrypted) doc = null  // pdf-lib cannot decrypt — its strings would be ciphertext
    return {
      title: raw?.title ?? deep?.fields.title ?? (doc ? safe(() => doc!.getTitle()) : null) ?? null,
      author: raw?.author ?? deep?.fields.author ?? (doc ? safe(() => doc!.getAuthor()) : null) ?? null,
      subject: raw?.subject ?? deep?.fields.subject ?? (doc ? safe(() => doc!.getSubject()) : null) ?? null,
      producer: raw?.producer ?? deep?.fields.producer ?? (doc ? safe(() => doc!.getProducer()) : null) ?? null,
      creator: raw?.creator ?? deep?.fields.creator ?? (doc ? safe(() => doc!.getCreator()) : null) ?? null,
      creation_date: raw?.creation_date ?? deep?.fields.creation_date ?? (doc ? safe(() => doc!.getCreationDate()?.toISOString() ?? null) : null) ?? null,
      modification_date: raw?.modification_date ?? deep?.fields.modification_date ?? (doc ? safe(() => doc!.getModificationDate()?.toISOString() ?? null) : null) ?? null,
      page_count: pageCount || deep?.page_count_estimate || 0,
      file_size_bytes: fileSize,
      parse_failed: !doc,
      info_revisions: deep?.revisions,
      encrypted: deep?.encrypted ?? isEncrypted,
      encrypt_dict_count: deep?.encrypt_dict_count ?? (isEncrypted ? 1 : 0),
    }
  } catch {
    return null
  }
}

/**
 * Tolerant deep scan — the fallback that does NOT depend on pdf-lib's strict
 * parser or on the Info dictionary sitting uncompressed in the byte stream.
 *
 * Case 24 (2026-08-21): pdf-lib threw on 5 of 6 uploaded PDFs (an edited
 * Equifax report, three Excel-made pay stubs, a Word letter) and the Info
 * dictionaries lived inside Flate-compressed object streams — so BOTH the
 * raw byte scan and pdf-lib came back empty, readPdfMetadata returned null,
 * and every metadata rule silently skipped. poppler read them all:
 * Created 2023, Author "Johnson Osei", Excel 2013, Modified 2026-08-13.
 *
 * Here every FlateDecode stream is inflated (DecompressionStream, available
 * on the edge and in Node 18+) and the inflated text is scanned for Info
 * keys. The LAST occurrence of each key wins — incremental updates append,
 * so the last one is the current revision — and distinct ModDate values
 * are counted as revisions.
 */
async function deepScanPdfMetadata(u8: Uint8Array): Promise<{
  fields: { title: string | null; author: string | null; subject: string | null; producer: string | null; creator: string | null; creation_date: string | null; modification_date: string | null }
  revisions: number
  page_count_estimate: number
  encrypted: boolean
  encrypt_dict_count: number
  decrypted: boolean
} | null> {
  const MAX_TOTAL = 24 * 1024 * 1024
  const latin1 = (b: Uint8Array) => {
    let out = ''
    const CH = 0x8000
    for (let i = 0; i < b.length; i += CH) out += String.fromCharCode.apply(null, Array.from(b.subarray(i, i + CH)) as unknown as number[])
    return out
  }
  const inflate = async (b: Uint8Array): Promise<string | null> => {
    try {
      if (typeof DecompressionStream === 'undefined') return null
      const ds = new DecompressionStream('deflate')
      const writer = ds.writable.getWriter()
      // Copy into a fresh ArrayBuffer-backed view — TS's BufferSource type
      // rejects a view over a possibly-shared buffer.
      void writer.write(new Uint8Array(b)).catch(() => {})
      void writer.close().catch(() => {})
      const buf = await new Response(ds.readable).arrayBuffer()
      return latin1(new Uint8Array(buf))
    } catch {
      return null
    }
  }
  try {
    const raw = latin1(u8)
    const encInfos = findEncryptInfos(u8)
    const encrypted = encInfos.length > 0
    let decrypted = false
    const chunks: string[] = encrypted ? [] : [raw]
    let total = 0
    const INFO_KEYS = ['Title', 'Author', 'Subject', 'Producer', 'Creator', 'CreationDate', 'ModDate']
    const esc = (v: Uint8Array) => latin1(v).replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)')
    const stripEol = (start: number, end: number) => {
      let e = end
      while (e > start && (u8[e - 1] === 0x0A || u8[e - 1] === 0x0D)) e--
      return e
    }

    if (encrypted) {
      // Encrypted file: try every /Encrypt dictionary (an incremental update
      // may have re-encrypted with a new one; the LAST is the current
      // revision). With the empty user password, walk every object: streams
      // are decrypted (then inflated) and scanned; Info-dictionary strings
      // are decrypted individually.
      for (const info of [...encInfos].reverse()) {
        const key = await computeFileKey(info)
        if (!key) continue
        const reObj = /(^|[^0-9])(\d+)\s+(\d+)\s+obj\b/g
        let om: RegExpExecArray | null
        let found = 0
        while ((om = reObj.exec(raw))) {
          const objNum = Number(om[2]), gen = Number(om[3])
          if (objNum === info.objNum) continue
          const bodyStart = om.index + om[0].length
          const bodyEnd = raw.indexOf('endobj', bodyStart)
          if (bodyEnd < 0) break
          const body = raw.slice(bodyStart, bodyEnd)
          const sIdx = body.search(/stream\r?\n/)
          if (sIdx >= 0) {
            const sm = body.slice(sIdx).match(/^stream\r?\n/)!
            const dataStart = bodyStart + sIdx + sm[0].length
            const endIdx = raw.indexOf('endstream', dataStart)
            if (endIdx < 0) continue
            const dataEnd = stripEol(dataStart, endIdx)
            const len = dataEnd - dataStart
            if (len <= 0 || len > 8 * 1024 * 1024) continue
            total += len
            if (total > MAX_TOTAL) break
            const dec = await decryptObjectBytes(info, key, objNum, gen, u8.subarray(dataStart, dataEnd), 'stream')
            if (!dec) continue
            const dictPart = body.slice(0, sIdx)
            const text = /\/FlateDecode/.test(dictPart) ? await inflate(dec) : latin1(dec)
            if (text) { chunks.push(text); found++ }
          } else if (INFO_KEYS.some(k => body.includes('/' + k))) {
            for (const k of INFO_KEYS) {
              const km = body.match(new RegExp(`/${k}\\s*`))
              if (!km || km.index === undefined) continue
              const sv = parsePdfStringAt(body, km.index + km[0].length)
              if (!sv) continue
              const dec = await decryptObjectBytes(info, key, objNum, gen, sv.bytes, 'string')
              if (dec) { chunks.push(`/${k} (${esc(dec)})`); found++ }
            }
          }
          reObj.lastIndex = bodyEnd
        }
        if (found > 0) { decrypted = true; break }
      }
    } else {
      const re = /\/Filter\s*(?:\/FlateDecode|\[\s*\/FlateDecode\s*\])[^]*?stream\r?\n/g
      let m: RegExpExecArray | null
      while ((m = re.exec(raw))) {
        const start = m.index + m[0].length
        const end = raw.indexOf('endstream', start)
        if (end < 0) break
        const len = end - start
        if (len <= 0 || len > 8 * 1024 * 1024) continue
        total += len
        if (total > MAX_TOTAL) break
        const text = await inflate(u8.subarray(start, end))
        if (text) chunks.push(text)
        re.lastIndex = end
      }
    }
    const all = chunks.join('\n')
    const grab = (key: string): { value: string | null; count: number } => {
      const rx = new RegExp(`/${key}\\s*(\\(((?:\\\\.|[^\\\\)])*)\\)|<([0-9A-Fa-f\\s]+)>)`, 'g')
      let last: string | null = null
      const seen = new Set<string>()
      let mm: RegExpExecArray | null
      while ((mm = rx.exec(all))) {
        let v: string
        if (mm[2] !== undefined) {
          v = mm[2].replace(/\\\\([()\\\\])/g, '$1')
          if (v.charCodeAt(0) === 0xFE && v.charCodeAt(1) === 0xFF) {
            let u = ''
            for (let i = 2; i + 1 < v.length; i += 2) u += String.fromCharCode((v.charCodeAt(i) << 8) | v.charCodeAt(i + 1))
            v = u
          }
        } else {
          const hex = (mm[3] || '').replace(/\s/g, '')
          let str = ''
          for (let i = 0; i + 1 < hex.length; i += 2) str += String.fromCharCode(parseInt(hex.slice(i, i + 2), 16))
          if (str.charCodeAt(0) === 0xFE && str.charCodeAt(1) === 0xFF) {
            let u = ''
            for (let i = 2; i + 1 < str.length; i += 2) u += String.fromCharCode((str.charCodeAt(i) << 8) | str.charCodeAt(i + 1))
            str = u
          }
          v = str
        }
        v = v.trim()
        if (!v) continue
        seen.add(v)
        last = v
      }
      return { value: last, count: seen.size }
    }
    const parseDate = (raw: string | null): string | null => {
      if (!raw) return null
      const m1 = raw.match(/D:(\d{4})(\d{2})(\d{2})(\d{2})?(\d{2})?(\d{2})?([+-Z])?(\d{2})?'?(\d{2})?/)
      if (!m1) return null
      const [, y, mo, d, h = '00', mi = '00', se = '00', tz, tzH, tzM] = m1
      const off = tz === '+' || tz === '-' ? `${tz}${tzH || '00'}:${tzM || '00'}` : 'Z'
      return `${y}-${mo}-${d}T${h}:${mi}:${se}${off}`
    }
    const title = grab('Title'), author = grab('Author'), subject = grab('Subject')
    const producer = grab('Producer'), creator = grab('Creator')
    const cdate = grab('CreationDate'), mdate = grab('ModDate')
    const nothing = !producer.value && !creator.value && !cdate.value && !mdate.value
    if (nothing && !encrypted) return null
    // Page objects, approximately: "/Type /Page" not followed by "s".
    const pageMatches = all.match(/\/Type\s*\/Page\b(?!s)/g)
    return {
      fields: {
        title: title.value, author: author.value, subject: subject.value,
        producer: producer.value, creator: creator.value,
        creation_date: parseDate(cdate.value), modification_date: parseDate(mdate.value),
      },
      revisions: Math.max(mdate.count, cdate.count),
      page_count_estimate: pageMatches ? pageMatches.length : 0,
      encrypted,
      encrypt_dict_count: encInfos.length,
      decrypted,
    }
  } catch {
    return null
  }
}

/**
 * Apply metadata-based fraud heuristics. Returns a list of ForensicFlag
 * objects. The `file` and `kind` arguments are used to make the flags
 * actionable and for kind-specific rules (e.g. bank statement strictness).
 */
export function checkPdfMetadata(
  meta: PdfMetadataResult,
  file: string,
  kind: string
): ForensicFlag[] {
  const flags: ForensicFlag[] = []
  const isStrict = STRICT_KINDS.has(kind)
  const producer = meta.producer || ''
  const creator = meta.creator || ''
  const title = meta.title || ''
  const combined = `${producer} ${creator}`
  const FINANCIAL = kind === 'bank_statement' || kind === 'credit_report' || kind === 'pay_stub'

  // ---------------------------------------------------------------------------
  // Rule 0a: the strict parser could not read the file. Bank/bureau/payroll
  // exports parse cleanly; files that have been through an editor (incremental
  // updates, rewritten xref streams) are what break it. Disclosed, not
  // swallowed — this used to render as "✓ 无异常".
  // ---------------------------------------------------------------------------
  // ---------------------------------------------------------------------------
  // Rule 0: encryption. Bank, bureau and payroll exports are never
  // password-protected; an applicant-encrypted file is either privacy-minded
  // or hiding an edit. TWO /Encrypt dictionaries means an incremental update
  // re-encrypted the file: it was edited and re-saved with protection on.
  // Case 24: all five edited documents were AES-256 with an empty user
  // password, the four financial ones re-encrypted after the edit.
  // ---------------------------------------------------------------------------
  if (meta.encrypted) {
    const re = (meta.encrypt_dict_count ?? 1) > 1
    if (re && FINANCIAL) {
      flags.push({
        code: 'pdf_reencrypted_after_edit',
        severity: 'high',
        file,
        evidence_en: `The file carries ${meta.encrypt_dict_count} encryption dictionaries: an incremental update re-encrypted it after the original save — the ${kind.replace('_', ' ')} was opened, edited and saved again with protection on. Bank, bureau and payroll exports are written once and never password-protected.`,
        evidence_zh: `文件内含 ${meta.encrypt_dict_count} 个加密字典：在原始保存之后，一次增量更新重新加密了它——这份${zhKind(kind)}被打开、编辑并再次带密码保存。银行/征信局/工资系统导出的文件是一次写成、从不加密的。`,
      })
    } else {
      flags.push({
        code: 'pdf_encrypted',
        severity: FINANCIAL ? 'medium' : 'low',
        file,
        evidence_en: `The PDF is encrypted (empty user password${meta.producer ? ', decrypted for analysis' : ' — contents could not be decrypted'}). ${FINANCIAL ? 'Bank, bureau and payroll systems do not password-protect their exports; the protection was added by whoever handled the file afterwards.' : 'Unusual for a letter exported directly from a word processor; verify the original.'}`,
        evidence_zh: `PDF 带加密（空用户密码${meta.producer ? '，已解密分析' : '——内容无法解密'}）。${FINANCIAL ? '银行/征信局/工资系统不会给导出文件加密；保护是之后经手文件的人加上的。' : '对直接从文字处理软件导出的信件来说不常见；请核对原件。'}`,
      })
    }
  }
  if (meta.parse_failed && isStrict && !meta.encrypted) {
    flags.push({
      code: 'pdf_parse_failed',
      severity: 'medium',
      file,
      evidence_en: `The PDF could not be parsed by a strict PDF reader (metadata recovered by a tolerant scan instead). Bank, bureau and payroll exports parse cleanly; a damaged cross-reference structure is typical of a file that has been opened, edited and re-saved.`,
      evidence_zh: `严格 PDF 解析器无法解析此文件（元数据由容错扫描恢复）。银行/征信局/工资系统导出的文件结构规整；交叉引用表损坏通常意味着文件被打开、编辑并重新保存过。`,
    })
  }
  if ((meta.info_revisions ?? 0) > 1 && FINANCIAL) {
    flags.push({
      code: 'pdf_info_revisions',
      severity: 'medium',
      file,
      evidence_en: `The file carries ${meta.info_revisions} distinct metadata revisions (incremental updates append a new Info dictionary each time the file is re-saved). A ${kind.replace('_', ' ')} exported once has exactly one.`,
      evidence_zh: `文件内含 ${meta.info_revisions} 个不同版本的元数据字典（每次重新保存都会追加一份）。一次性导出的${zhKind(kind)}只有一份。`,
    })
  }

  // ---------------------------------------------------------------------------
  // Rule 0b: a PERSONAL author on a financial document. Payroll, bank and
  // bureau systems stamp no Author (or a system/company string); a human name
  // means a person's desktop application wrote the file. Case 24: three
  // "ADP" pay stubs, Author "Johnson Osei.".
  // ---------------------------------------------------------------------------
  const author = (meta.author || '').trim()
  if (FINANCIAL && author) {
    const looksPersonal = /^[A-Za-z][A-Za-z'’.-]+(?:\s+[A-Za-z][A-Za-z'’.-]+){1,2}\.?$/.test(author)
      && !/\b(inc|ltd|corp|bank|payroll|systems?|services?|adp|ceridian|workday|equifax|transunion|server|generator)\b/i.test(author)
    if (looksPersonal) {
      flags.push({
        code: 'pdf_author_personal',
        severity: 'medium',
        file,
        evidence_en: `PDF Author is a personal name ("${author}"). Payroll, bank and bureau exports carry no personal author — a named author means the file was produced from someone's desktop application.`,
        evidence_zh: `PDF 作者字段是一个人名（"${author}"）。工资系统/银行/征信局导出的文件不会带个人作者——有具名作者说明文件出自某人的桌面软件。`,
      })
    }
  }

  // ---------------------------------------------------------------------------
  // Rule 0c: the title betrays an office-document source on a financial kind
  // ("Microsoft Word - NEHroughemploy.docx", "payslip.xlsx"). Employment
  // letters are legitimately Word documents; statements and stubs are not.
  // ---------------------------------------------------------------------------
  if (FINANCIAL && /\.(docx?|xlsx?|pages|numbers)\b|Microsoft\s+(Word|Excel)\s*-/i.test(title)) {
    flags.push({
      code: 'pdf_title_office_source',
      severity: 'medium',
      file,
      evidence_en: `PDF title "${title}" names an office document source. A ${kind.replace('_', ' ')} produced by a bank, bureau or payroll system does not originate from a Word/Excel file.`,
      evidence_zh: `PDF 标题 "${title}" 暴露了办公文档来源。银行/征信局/工资系统生成的${zhKind(kind)}不会来自 Word/Excel 文件。`,
    })
  }

  // ---------------------------------------------------------------------------
  // Rule 1: Check Producer/Creator against categorized tool lists.
  //
  // Image EDITING tools (Photoshop, GIMP, Canva) → always suspicious
  // Doc CREATION tools (Word, Pages) → suspicious for bank/credit/pay, but
  //   normal for employment_letter and offer_letter
  // SCAN/PRINT tools (iOS Notes, Print to PDF) → LEGITIMATE for all types,
  //   because people commonly scan/photo physical documents
  // IMAGE CONVERTERS (Image2PDF) → suspicious for strict doc types
  // ---------------------------------------------------------------------------
  let producerFlagged = false

  // 1a. Editing tools — always suspicious for any strict kind
  for (const { pattern, tool } of EDITING_TOOL_PATTERNS) {
    if (pattern.test(combined)) {
      flags.push({
        code: 'pdf_producer_consumer_tool',
        severity: isStrict ? 'critical' : 'high',
        file,
        evidence_en: `PDF Producer="${producer || creator}" indicates ${tool} — an image editing tool. Documents edited in ${tool} are highly likely to be tampered.`,
        evidence_zh: `PDF 生成工具为 "${producer || creator}"（${tool}），这是图片编辑软件。经过 ${tool} 编辑的文件极可能被篡改。`,
      })
      producerFlagged = true
      break
    }
  }

  // 1b. Doc creation tools — suspicious for bank_statement/credit_report/pay_stub
  //     but NORMAL for employment_letter/offer_letter (often typed in Word).
  //     Pay stubs get their OWN code: very small employers genuinely produce
  //     stubs from Word/Excel templates, so a Word stub is a high-severity
  //     verify signal but NOT the standalone producer_consumer_tool hard gate
  //     that bank statements and credit reports (never legitimately produced
  //     by Word) carry.
  if (!producerFlagged) {
    const docToolGating = kind === 'bank_statement' || kind === 'credit_report'
    const docToolSuspicious = docToolGating || kind === 'pay_stub'
    for (const { pattern, tool } of DOC_CREATION_PATTERNS) {
      if (pattern.test(combined)) {
        if (docToolSuspicious) {
          flags.push({
            code: docToolGating ? 'pdf_producer_consumer_tool' : 'pdf_producer_paystub_doc_tool',
            severity: 'high',
            file,
            evidence_en: `PDF Producer="${producer || creator}" indicates ${tool}. Real ${kind.replace('_', ' ')} PDFs are ${docToolGating ? 'server-generated — ' + tool + ' suggests manual creation.' : 'usually server-generated; ' + tool + ' is consistent with a very small employer\'s manual template, but also with fabrication — verify with the employer.'}`,
            evidence_zh: `PDF 生成工具为 "${producer || creator}"（${tool}）。${docToolGating ? `真实的${zhKind(kind)}由服务器生成，${tool} 表明是手工制作的。` : `真实的${zhKind(kind)}通常由工资系统生成；${tool} 可能是小微雇主手工模板，也可能是伪造——建议向雇主核实。`}`,
          })
          producerFlagged = true
        }
        // For employment_letter/offer_letter, Word/Pages is normal — no flag
        break
      }
    }
  }

  // 1c. Image converters — suspicious for strict kinds
  if (!producerFlagged) {
    for (const { pattern, tool } of IMAGE_CONVERTER_PATTERNS) {
      if (pattern.test(combined)) {
        flags.push({
          code: 'pdf_producer_consumer_tool',
          severity: isStrict ? 'high' : 'medium',
          file,
          evidence_en: `PDF Producer="${producer || creator}" indicates ${tool}. Official documents are not typically distributed as converted images.`,
          evidence_zh: `PDF 生成工具为 "${producer || creator}"（${tool}）。正式文件通常不会以图片转换的方式发放。`,
        })
        producerFlagged = true
        break
      }
    }
  }

  // 1d. Scan/print tools — LEGITIMATE, no flag. iOS Notes, Print to PDF,
  //     CamScanner etc. are standard ways to digitize physical documents.

  // ---------------------------------------------------------------------------
  // Rule 2: Title or Subject mentions image/screenshot extension. The Title
  // field in a real bank PDF is either empty or the account/statement number.
  // It would NEVER contain "PNG" or "screenshot".
  // ---------------------------------------------------------------------------
  if (IMAGE_TITLE_PATTERN.test(title) || IMAGE_TITLE_PATTERN.test(meta.subject || '')) {
    flags.push({
      code: 'pdf_title_indicates_image',
      severity: isStrict ? 'critical' : 'high',
      file,
      evidence_en: `PDF internal title="${title || meta.subject}" indicates the source was an image file (PNG/JPEG/screenshot) before being converted to PDF.`,
      evidence_zh: `PDF 内部标题="${title || meta.subject}"，说明源文件是图片（PNG/JPEG/截图），后被转换成 PDF。`,
    })
  }

  // ---------------------------------------------------------------------------
  // Rule 3: For strict kinds, having NO trusted producer string is itself a
  // soft warning. Combined with Rule 1 it's already critical; standalone it's
  // medium.
  // ---------------------------------------------------------------------------
  if (isStrict) {
    const hasTrusted = TRUSTED_PRODUCER_PATTERNS.some(p => p.test(combined))
    const hasScreenshotTool = SCREENSHOT_PRODUCER_PATTERNS.some(({ pattern }) => pattern.test(combined))
    const hasRecognized = RECOGNIZED_PRODUCER_PATTERNS.some(p => p.test(combined))
    if (!hasTrusted && !hasScreenshotTool && !hasRecognized && producer) {
      flags.push({
        code: 'pdf_producer_unknown',
        severity: 'low',
        file,
        evidence_en: `PDF Producer="${producer}" is not in the known whitelist of bank/payroll systems. Authentic source could not be confirmed from metadata alone.`,
        evidence_zh: `PDF 生成工具="${producer}" 不在已知的银行/工资系统白名单中。仅凭元数据无法确认文件出处。`,
      })
    }
  }

  // ---------------------------------------------------------------------------
  // Rule 4: Metadata stripped (no Producer at all). Common in re-saved PDFs.
  // Real server-generated PDFs always set Producer.
  // ---------------------------------------------------------------------------
  if (!meta.encrypted && !producer && !creator && isStrict) {
    flags.push({
      code: 'pdf_metadata_stripped',
      severity: 'medium',
      file,
      evidence_en: `PDF has no Producer or Creator metadata. Authentic ${kind || 'official'} PDFs always include their generating tool.`,
      evidence_zh: `PDF 完全没有生成工具元数据。真实的${zhKind(kind)}文件总会包含生成工具信息。`,
    })
  }

  // ---------------------------------------------------------------------------
  // Rule 5: Fresh creation timestamp. Real bank statements and pay stubs are
  // dated as of the statement/pay period (often weeks before download); a
  // fresh CreationDate matching ModDate exactly suggests "just built from
  // scratch".
  //
  // EXCLUDES kinds that are EXPECTED to be freshly downloaded:
  //   - credit_report — landlords always pull a fresh copy from the bureau
  //   - employment_letter — agents commonly export/sign these the same day
  //   - id_document — passports/licences are routinely re-scanned on demand
  //   - other / bundled exports — agent packets export to PDF on demand
  // The rule still fires for bank_statement and pay_stub where freshness IS
  // suspicious.
  // ---------------------------------------------------------------------------
  const FRESHNESS_KINDS = new Set(['bank_statement', 'pay_stub'])
  if (
    FRESHNESS_KINDS.has(kind) &&
    meta.creation_date &&
    meta.modification_date &&
    meta.creation_date === meta.modification_date
  ) {
    const created = new Date(meta.creation_date).getTime()
    const ageHours = (Date.now() - created) / (1000 * 60 * 60)
    if (ageHours < 24 * 7 && ageHours >= 0) {
      flags.push({
        code: 'pdf_freshly_created',
        severity: 'medium',
        file,
        evidence_en: `${kind} PDF was created within the past ${Math.round(ageHours)}h with CreationDate==ModificationDate. Authentic ${kind === 'bank_statement' ? 'bank statements' : 'pay stubs'} are typically weeks-to-months old by the time they're shared with a landlord.`,
        evidence_zh: `${zhKind(kind)} PDF 创建时间在 ${Math.round(ageHours)} 小时内，且创建时间等于修改时间。真实的${zhKind(kind)}给到房东时通常已经存在好几周到几个月。`,
      })
    }
  }

  // ---------------------------------------------------------------------------
  // Rule 6: For strict kinds, single-page PDFs are suspicious. Real bank
  // statements are typically 2-6 pages; credit reports are 5-20 pages.
  // ---------------------------------------------------------------------------
  if (isStrict && meta.page_count === 1 && (kind === 'bank_statement' || kind === 'credit_report')) {
    flags.push({
      code: 'pdf_unusually_short',
      severity: 'low',
      file,
      evidence_en: `${kind} is only 1 page. Authentic ${kind === 'bank_statement' ? 'bank statements (2-6 pages)' : 'credit reports (5-20 pages)'} are typically longer.`,
      evidence_zh: `${zhKind(kind)}只有 1 页。真实的${kind === 'bank_statement' ? '银行对账单通常 2-6 页' : '信用报告通常 5-20 页'}。`,
    })
  }

  return flags
}

function zhKind(kind: string): string {
  switch (kind) {
    case 'bank_statement': return '银行对账单'
    case 'credit_report': return '信用报告'
    case 'pay_stub': return '工资单'
    case 'employment_letter': return '雇佣证明信'
    case 'id_document': return '身份证件'
    case 'reference': return '推荐信'
    case 'offer_letter': return 'Offer Letter'
    default: return '官方文件'
  }
}
