// -----------------------------------------------------------------------------
// P0 — PDF Metadata Forensics
//
// Reads PDF Title / Producer / Creator / CreationDate / ModificationDate using
// pdf-lib (pure JS, edge-runtime compatible). Then applies heuristics to flag
// PDFs that look like they were created by manually re-saving a screenshot,
// rather than being generated by the original source server (bank, Equifax,
// employer payroll system).
//
// Real bank/credit-bureau PDFs have specific Producer signatures:
//   - CIBC online statements: "iText" (varies by version, e.g. "iText 5.5.13")
//   - RBC online statements: "Adobe Acrobat" or "Apache FOP"
//   - TD online statements:   "Apache FOP"
//   - Equifax credit reports: server-generated text PDF (specific layout)
//   - ADP / Ceridian paystubs: "Apache FOP" or "Crystal Reports"
//
// Forged PDFs almost always come from re-saving a doctored screenshot, so the
// Producer ends up being the user's local image-to-PDF converter:
//   - macOS Preview:  Producer="macOS Version X.Y.Z (Build) Quartz PDFContext"
//                     Creator="Preview" (often, not always)
//   - Microsoft Word: Producer="Microsoft Word" or "Microsoft® Word for Microsoft 365"
//   - Skia (Chrome Print to PDF): Producer="Skia/PDF m1XX"
//   - Pages (macOS):  Producer="macOS Version X.Y.Z Quartz PDFContext"
//                     Creator="Pages"
//   - GIMP/Photoshop export: Producer contains "GIMP" or "Adobe Photoshop"
//
// We also flag titles that mention PNG/JPEG/screenshot — these strings only
// appear in the title field when the user manually saved a screenshot file.
// Real bank PDFs have titles like "Account_Statement_2026-03.pdf" or empty.
// -----------------------------------------------------------------------------

import { PDFDocument } from 'pdf-lib'
import type { ForensicFlag, PdfMetadataResult } from './types'

/** Document kinds where forged screenshots are most common (bank docs,
 *  credit reports, paystubs) — we apply stricter Producer rules to these. */
const STRICT_KINDS = new Set([
  'bank_statement',
  'credit_report',
  'pay_stub',
  'employment_letter',
])

/** Producer strings seen in screenshot-derived PDFs — strong fraud signal
 *  when document kind is in STRICT_KINDS. */
const SCREENSHOT_PRODUCER_PATTERNS: Array<{ pattern: RegExp; tool: string }> = [
  { pattern: /Quartz\s*PDFContext/i,        tool: 'macOS Preview/Quartz' },
  { pattern: /Skia[\/\s]?PDF/i,             tool: 'Chrome Print-to-PDF' },
  { pattern: /Microsoft\s*Word/i,           tool: 'Microsoft Word' },
  { pattern: /Microsoft.*Office/i,          tool: 'Microsoft Office' },
  { pattern: /Pages\s+\d/i,                 tool: 'Apple Pages' },
  { pattern: /LibreOffice/i,                tool: 'LibreOffice' },
  { pattern: /OpenOffice/i,                 tool: 'OpenOffice' },
  { pattern: /Google\s*Docs/i,              tool: 'Google Docs export' },
  { pattern: /GIMP/i,                       tool: 'GIMP image editor' },
  { pattern: /Photoshop/i,                  tool: 'Adobe Photoshop' },
  { pattern: /Image2PDF/i,                  tool: 'Image2PDF converter' },
  { pattern: /jpeg2pdf|jpg2pdf|png2pdf/i,   tool: 'image-to-PDF converter' },
  { pattern: /Canva/i,                      tool: 'Canva' },
]

/** Producer/Creator strings indicating a real server-generated PDF.
 *  Presence does NOT prove authenticity (a sophisticated forger could spoof
 *  the metadata) but absence of these in conjunction with screenshot tools
 *  is strong evidence of forgery. */
const TRUSTED_PRODUCER_PATTERNS: RegExp[] = [
  /iText\s*[\d.]/i,           // CIBC, BMO, many Java enterprise PDFs
  /Apache\s*FOP/i,            // RBC, TD, payroll systems
  /Crystal\s*Reports/i,       // ADP, Ceridian, enterprise reports
  /Adobe\s*PDF\s*Library/i,   // Adobe enterprise tooling
  /Prince\s*[\d.]/i,          // Prince XML — common for fintech
  /wkhtmltopdf/i,             // server-side rendering (less trusted but common)
  /PDFKit/i,                  // Node.js PDFKit — server-generated
  /ReportLab/i,               // Python ReportLab — server-generated
  /TCPDF/i,                   // PHP TCPDF — server-generated
  /FPDF/i,                    // PHP FPDF — server-generated
  /OpenPDF/i,                 // Java OpenPDF — server-generated
]

/** Title patterns that indicate the source file was an image (PNG/JPEG/screenshot)
 *  before being converted to PDF — strong fraud signal. */
const IMAGE_TITLE_PATTERN = /\b(PNG|JPEG|JPG|screenshot|screen[\s-]?shot|image|scan|untitled|export)\b/i

/**
 * Read PDF metadata. Returns null if the buffer isn't a parseable PDF.
 */
export async function readPdfMetadata(
  bytes: ArrayBuffer | Uint8Array
): Promise<PdfMetadataResult | null> {
  try {
    // pdf-lib needs Uint8Array. ignoreEncryption=true so we can still read
    // the metadata of password-protected PDFs (rare in tenant docs).
    const doc = await PDFDocument.load(bytes, {
      ignoreEncryption: true,
      throwOnInvalidObject: false,
    })

    const fileSize = bytes instanceof Uint8Array ? bytes.byteLength : bytes.byteLength

    return {
      title: doc.getTitle() || null,
      author: doc.getAuthor() || null,
      subject: doc.getSubject() || null,
      producer: doc.getProducer() || null,
      creator: doc.getCreator() || null,
      creation_date: doc.getCreationDate()?.toISOString() || null,
      modification_date: doc.getModificationDate()?.toISOString() || null,
      page_count: doc.getPageCount(),
      file_size_bytes: fileSize,
    }
  } catch {
    return null
  }
}

/**
 * Apply metadata-based fraud heuristics. Returns a list of ForensicFlag
 * objects. The `file` and `kind` arguments are used to make the flags
 * actionable and for kind-specific rules (e.g. bank statement strictness).
 */
export function checkPdfMetadata(
  meta: PdfMetadataResult,
  file: string,
  kind: string
): ForensicFlag[] {
  const flags: ForensicFlag[] = []
  const isStrict = STRICT_KINDS.has(kind)
  const producer = meta.producer || ''
  const creator = meta.creator || ''
  const title = meta.title || ''
  const combined = `${producer} ${creator}`

  // ---------------------------------------------------------------------------
  // Rule 1: Producer is a known screenshot/image-to-PDF tool, AND doc claims
  // to be from a bank / credit bureau / employer. This is the strongest signal
  // we have — real CIBC/RBC/Equifax/ADP PDFs are NEVER produced by Preview.
  // ---------------------------------------------------------------------------
  for (const { pattern, tool } of SCREENSHOT_PRODUCER_PATTERNS) {
    if (pattern.test(combined)) {
      const sev = isStrict ? 'critical' : 'medium'
      flags.push({
        code: 'pdf_producer_consumer_tool',
        severity: sev,
        file,
        evidence_en: `PDF Producer="${producer || creator}" indicates ${tool}. Real ${kind || 'official'} PDFs come from server-side tools (iText, Apache FOP, Crystal Reports), not desktop image converters.`,
        evidence_zh: `PDF 生成工具为 "${producer || creator}"（${tool}）。真实的${zhKind(kind)}通常由服务器生成（iText、Apache FOP、Crystal Reports 等），不会用桌面图片转换器。`,
      })
      break  // one match is enough
    }
  }

  // ---------------------------------------------------------------------------
  // Rule 2: Title or Subject mentions image/screenshot extension. The Title
  // field in a real bank PDF is either empty or the account/statement number.
  // It would NEVER contain "PNG" or "screenshot".
  // ---------------------------------------------------------------------------
  if (IMAGE_TITLE_PATTERN.test(title) || IMAGE_TITLE_PATTERN.test(meta.subject || '')) {
    flags.push({
      code: 'pdf_title_indicates_image',
      severity: isStrict ? 'critical' : 'high',
      file,
      evidence_en: `PDF internal title="${title || meta.subject}" indicates the source was an image file (PNG/JPEG/screenshot) before being converted to PDF.`,
      evidence_zh: `PDF 内部标题="${title || meta.subject}"，说明源文件是图片（PNG/JPEG/截图），后被转换成 PDF。`,
    })
  }

  // ---------------------------------------------------------------------------
  // Rule 3: For strict kinds, having NO trusted producer string is itself a
  // soft warning. Combined with Rule 1 it's already critical; standalone it's
  // medium.
  // ---------------------------------------------------------------------------
  if (isStrict) {
    const hasTrusted = TRUSTED_PRODUCER_PATTERNS.some(p => p.test(combined))
    const hasScreenshotTool = SCREENSHOT_PRODUCER_PATTERNS.some(({ pattern }) => pattern.test(combined))
    if (!hasTrusted && !hasScreenshotTool && producer) {
      flags.push({
        code: 'pdf_producer_unknown',
        severity: 'low',
        file,
        evidence_en: `PDF Producer="${producer}" is not in the known whitelist of bank/payroll systems. Authentic source could not be confirmed from metadata alone.`,
        evidence_zh: `PDF 生成工具="${producer}" 不在已知的银行/工资系统白名单中。仅凭元数据无法确认文件出处。`,
      })
    }
  }

  // ---------------------------------------------------------------------------
  // Rule 4: Metadata stripped (no Producer at all). Common in re-saved PDFs.
  // Real server-generated PDFs always set Producer.
  // ---------------------------------------------------------------------------
  if (!producer && !creator && isStrict) {
    flags.push({
      code: 'pdf_metadata_stripped',
      severity: 'medium',
      file,
      evidence_en: `PDF has no Producer or Creator metadata. Authentic ${kind || 'official'} PDFs always include their generating tool.`,
      evidence_zh: `PDF 完全没有生成工具元数据。真实的${zhKind(kind)}文件总会包含生成工具信息。`,
    })
  }

  // ---------------------------------------------------------------------------
  // Rule 5: Creation and modification dates are identical AND within the past
  // 7 days. Real bank statements are dated as of the statement period, often
  // weeks/months before the user downloads them. A fresh CreationDate matching
  // ModDate exactly suggests "just created from scratch".
  // ---------------------------------------------------------------------------
  if (meta.creation_date && meta.modification_date && meta.creation_date === meta.modification_date) {
    const created = new Date(meta.creation_date).getTime()
    const ageHours = (Date.now() - created) / (1000 * 60 * 60)
    if (ageHours < 24 * 7 && ageHours >= 0) {
      flags.push({
        code: 'pdf_freshly_created',
        severity: isStrict ? 'medium' : 'low',
        file,
        evidence_en: `PDF was created within the past ${Math.round(ageHours)}h with CreationDate==ModificationDate. Suggests just-built file rather than archived statement.`,
        evidence_zh: `PDF 创建时间在 ${Math.round(ageHours)} 小时内，且创建时间等于修改时间。看起来是刚做出来的文件，不是历史保存的对账单。`,
      })
    }
  }

  // ---------------------------------------------------------------------------
  // Rule 6: For strict kinds, single-page PDFs are suspicious. Real bank
  // statements are typically 2-6 pages; credit reports are 5-20 pages.
  // ---------------------------------------------------------------------------
  if (isStrict && meta.page_count === 1 && (kind === 'bank_statement' || kind === 'credit_report')) {
    flags.push({
      code: 'pdf_unusually_short',
      severity: 'low',
      file,
      evidence_en: `${kind} is only 1 page. Authentic ${kind === 'bank_statement' ? 'bank statements (2-6 pages)' : 'credit reports (5-20 pages)'} are typically longer.`,
      evidence_zh: `${zhKind(kind)}只有 1 页。真实的${kind === 'bank_statement' ? '银行对账单通常 2-6 页' : '信用报告通常 5-20 页'}。`,
    })
  }

  return flags
}

function zhKind(kind: string): string {
  switch (kind) {
    case 'bank_statement': return '银行对账单'
    case 'credit_report': return '信用报告'
    case 'pay_stub': return '工资单'
    case 'employment_letter': return '雇佣证明信'
    case 'id_document': return '身份证件'
    case 'reference': return '推荐信'
    case 'offer_letter': return 'Offer Letter'
    default: return '官方文件'
  }
}
